### PR TITLE
Call for Papers, Schedule, and others

### PR DESCRIPTION
**Pull request by gsilano**
Call for Papers, Supporters, Schedule, Covered Topic now included on website.

Could you make it nicer? I'm not a Jekyll expert. In particular,

* Correct the text in the "Important Dates" section.
* Please check the topics. If you agree with them, we may decide to remove the bold text. We also need to create a short redirect on the top right side of the website.
* The same goes for the "Call for Papers". Let me know if the text suits you or you would like to say more. We may add a link to the ICRA website or the LaTeX and Word templates.
* Program, to be updated as soon as we have confirmation from the speakers.
* Steering Committee, we need to fix the size of the images.
* Support, we need to add logos of projects that will support us. It would be nice to have something similar to what we have with our photos, that would help. We need pictures. We could add a URL above them so they can be clicked.

I think that's all for now.

### CODE REVIEW

**Comment by gsilano** [comment]
Missing features

- [ ] Location (room). Waiting for ICRA'23 oraganizers.
- [ ] Accepted papers (list of the papers + link to the PDF)
- [ ] Discussion themes
- [x] Link to the Google Group (for receive notifications about the workshop)
- [ ] We may mention the guidelines (workshop outcome). For instance, we may create a section and announce it.
- [ ] Some text explaining that the workshop will follow an hybrid format, both physical and virtual.
- [x] We need to add an Endorsement section. This workshop is supported by the IEEE RAS TC on ARUAV ([AERIAL ROBOTICS AND UNMANNED AERIAL VEHICLES](https://www.ieee-ras.org/aerial-robotics-and-unmanned-aerial-vehicles)

**Comment by knmcguire** [comment]
I wonder if it would be better to intergrate the text in .rst or .md files... but I'm not sure if we will have that much more to add in terms of text but perhaps it will be easier for non-jekyll users to add new info

**Comment by gsilano** [comment]
If we have a structure, I can contribute. However, it takes a long time to create a new one from scratch.

**Comment by knmcguire** [comment]
I've managed to do all from the first list except the parts of support since I don't have that info, but we can add that to the second list of yours

**Pull request merged**
